apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-react-app-depl
specs: 
  selector: 
    matchLabels: 
     app: react-app
  replicas: 1
  template: 
    metadata: 
     labels:
      app: react-app
    spec: 
      containers:
        - name: react-app
          image: ayushthakur/my-react-app
---
apiVersion: v1
kind: service
metadata: 
  name: my-react-app-srv
spec: 
  type: NodePort
  selector: 
    app: react-app
  ports: 
   - name: my-port
     port: 3000
     targetPort: 3000